version: "3.9"

services:
  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=COLOQUE_AQUI_SEU_TOKEN_FORTE
      - DATABASE_ENABLED=false         # (ou true + config de Postgres, se quiser persistência completa)
    restart: unless-stopped
